Add flow definitions
mostjs/multicast pull request #27
Opened 2017-08-31 20:28 UTC by TrySound

2017-08-31 21:09 UTC, TrySound commented
Why do you guys commit dist in repo?

2017-09-25 00:31 UTC, briancavalier requested changes
Couple of very minor things.  Otherwise, looks good.

2017-09-25 00:31 UTC, briancavalier commented on src/index.js.flow
> +import { Stream, } from "most";
Our code style uses single quotes for imports (except in TS type def files).  Let's make these single quotes.

Also, remove trailing command in the second import.

2017-09-25 00:31 UTC, briancavalier commented on src/index.js.flow
> +  run (sink: Sink<A>, scheduler: Scheduler): Disposable<A>;
Extra space here.  I realize this was probably copied from the TS defs, so we can fix it there too.

2017-09-28 01:53 UTC, briancavalier approved these changes

2017-09-28 01:54 UTC, briancavalier commented
Thanks @TrySound!  You are a flow-type-adding machine! 😄

2017-09-28 01:54 UTC, merged

2022-03-20 01:34 UTC, popeda97 reviewed
#package.json